function planaqua = uploading_firesting_2020(filename, dataLines)
%IMPORTFILE Import data from a text file
%  PLANAQUA = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  PLANAQUA = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  planaqua = importfile("C:\Users\g.calabro-souza\Documents\Doctorat\Planaqua campaign 2020\Oxygen\20201013-planaqua.txt", [11, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 21-Oct-2020 09:59:10

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [19, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 31);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5", "Oxygen", "Oxygen1", "Oxygen2", "Compensation", "Temperature", "C", "VarName12", "Pressure", "Humidity", "TempProbe", "IntTemp", "AnalogIn", "RawData", "dphi", "VarName20", "VarName21", "Signal", "Intensity", "mV", "VarName25", "Ambient", "Light", "mV1", "VarName29", "AdvancedRawValuesonlyLoggedWhileRawDataWindowIsOpen", "VarName31"];
opts.VariableTypes = ["datetime", "datetime", "double", "string", "categorical", "double", "double", "double", "categorical", "double", "double", "double", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "double", "double", "double", "categorical", "double", "double", "double", "categorical", "double", "double", "double", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["VarName4", "AdvancedRawValuesonlyLoggedWhileRawDataWindowIsOpen", "VarName31"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["VarName4", "VarName5", "Compensation", "Pressure", "Humidity", "TempProbe", "IntTemp", "AnalogIn", "RawData", "Signal", "Ambient", "AdvancedRawValuesonlyLoggedWhileRawDataWindowIsOpen", "VarName31"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "VarName1", "InputFormat", "dd/MM/yyyy");
opts = setvaropts(opts, "VarName2", "InputFormat", "HH:mm:ss");
opts = setvaropts(opts, ["VarName3", "Oxygen", "Oxygen1", "Oxygen2", "Temperature", "C", "VarName12", "dphi", "VarName20", "VarName21", "Intensity", "mV", "VarName25", "Light", "mV1", "VarName29"], "DecimalSeparator", ",");
opts = setvaropts(opts, ["VarName3", "Oxygen", "Oxygen1", "Oxygen2", "Temperature", "C", "VarName12", "dphi", "VarName20", "VarName21", "Intensity", "mV", "VarName25", "Light", "mV1", "VarName29"], "ThousandsSeparator", ".");

% Import the data
planaqua = readtable(filename, opts);

end